[package]
name = "charity-sc-factory-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.charity-sc-factory]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.57.0"
default-features = false
